In [1]:
import pandas as pd

## 1.1 Read CSV Files
Load Density and Real Estate files

In [2]:
density_df = pd.read_csv('Density.csv', index_col=False)
density_df.head()

   FIPS          county state  2016  2017  2018  2019  2020
0  1001  Autauga County    AL    92    93    93    93    98
1  1003  Baldwin County    AL   130   133   137   140   145
2  1005  Barbour County    AL    29    28    28    27    28
3  1007     Bibb County    AL    36    36    35    35    35
4  1009   Blount County    AL    89    89    89    89    91

In [3]:
density_df.shape

(3140, 8)

In [4]:
density_df = density_df[['FIPS', 'county', 'state', '2020']]
density_df.head(10)

   FIPS           county state  2020
0  1001   Autauga County    AL    98
1  1003   Baldwin County    AL   145
2  1005   Barbour County    AL    28
3  1007      Bibb County    AL    35
4  1009    Blount County    AL    91
5  1011   Bullock County    AL    16
6  1013    Butler County    AL    24
7  1015   Calhoun County    AL   192
8  1017  Chambers County    AL    58
9  1019  Cherokee County    AL    45

In [5]:
re_df = pd.read_csv('Real_Estate.csv', index_col=False)
re_df.head()

C:\Users\Pc\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3146: DtypeWarning: Columns (37,38) have mixed types.Specify dtype option on import or set low_memory=False.
  has_raised = await self.run_ast_nodes(code_ast.body, cell_name,

,date,FIPS,county_name,median_listing_price,median_listing_price_mm,median_listing_price_yy,active_listing_count,active_listing_count_mm,active_listing_count_yy,median_days_on_market,...,total_listing_count_mm,total_listing_count_yy,pending_ratio,pending_ratio_mm,pending_ratio_yy,quality_flag,month,year,county,state
0,2016-07-01,2013,"aleutians east, ak",485000.0,NaN,NaN,3.0,NaN,NaN,612.0,...,NaN,NaN,NaN,NaN,NaN,NaN,7,2016,Aleutians East,AK
1,2016-08-01,2013,"aleutians east, ak",485000.0,NaN,NaN,4.0,NaN,NaN,644.0,...,NaN,NaN,NaN,NaN,NaN,NaN,8,2016,Aleutians East,AK
2,2016-09-01,2013,"aleutians east, ak",485000.0,NaN,NaN,4.0,NaN,NaN,665.0,...,NaN,NaN,NaN,NaN,NaN,NaN,9,2016,Aleutians East,AK
3,2016-10-01,2013,"aleutians east, ak",199500.0,NaN,NaN,4.0,NaN,NaN,449.0,...,NaN,NaN,NaN,NaN,NaN,NaN,10,2016,Aleutians East,AK
4,2016-11-01,2013,"aleutians east, ak",485000.0,NaN,NaN,4.0,NaN,NaN,735.0,...,NaN,NaN,NaN,NaN,NaN,NaN,11,2016,Aleutians East,AK

In [6]:
re_df.shape

(207513, 44)

## 1.2 Merged the Dataframe

In [12]:
df = re_df.merge(density_df, how='inner', left_on='FIPS', right_on='FIPS').drop(['county_name', 'state_x', 'county_x'], axis=1)
df.head()

,date,FIPS,median_listing_price,median_listing_price_mm,median_listing_price_yy,active_listing_count,active_listing_count_mm,active_listing_count_yy,median_days_on_market,median_days_on_market_mm,...,total_listing_count_yy,pending_ratio,pending_ratio_mm,pending_ratio_yy,quality_flag,month,year,county_y,state_y,2020
0,2016-07-01,2013,485000.0,NaN,NaN,3.0,NaN,NaN,612.0,NaN,...,NaN,NaN,NaN,NaN,NaN,7,2016,Aleutians East Borough,AK,0
1,2016-08-01,2013,485000.0,NaN,NaN,4.0,NaN,NaN,644.0,NaN,...,NaN,NaN,NaN,NaN,NaN,8,2016,Aleutians East Borough,AK,0
2,2016-09-01,2013,485000.0,NaN,NaN,4.0,NaN,NaN,665.0,NaN,...,NaN,NaN,NaN,NaN,NaN,9,2016,Aleutians East Borough,AK,0
3,2016-10-01,2013,199500.0,NaN,NaN,4.0,NaN,NaN,449.0,NaN,...,NaN,NaN,NaN,NaN,NaN,10,2016,Aleutians East Borough,AK,0
4,2016-11-01,2013,485000.0,NaN,NaN,4.0,NaN,NaN,735.0,NaN,...,NaN,NaN,NaN,NaN,NaN,11,2016,Aleutians East Borough,AK,0

In [8]:
# Reorder the columns
df.columns

Index(['date', 'FIPS', 'median_listing_price', 'median_listing_price_mm',
       'median_listing_price_yy', 'active_listing_count',
       'active_listing_count_mm', 'active_listing_count_yy',
       'median_days_on_market', 'median_days_on_market_mm',
       'median_days_on_market_yy', 'new_listing_count', 'new_listing_count_mm',
       'new_listing_count_yy', 'price_increased_count',
       'price_increased_count_mm', 'price_increased_count_yy',
       'price_reduced_count', 'price_reduced_count_mm',
       'price_reduced_count_yy', 'pending_listing_count',
       'pending_listing_count_mm', 'pending_listing_count_yy',
       'median_listing_price_per_square_foot',
       'median_listing_price_per_square_foot_mm',
       'median_listing_price_per_square_foot_yy', 'median_square_feet',
       'median_square_feet_mm', 'median_square_feet_yy',
       'average_listing_price', 'average_listing_price_mm',
       'average_listing_price_yy', 'total_listing_count',
       'total_listing_count_mm', 'total_listing_count_yy', 'pending_ratio',
       'pending_ratio_mm', 'pending_ratio_yy', 'quality_flag', 'month', 'year',
       'county_y', 'state_y', '2020'],
      dtype='object')

In [14]:
# Assign new order
column = ['FIPS', 'date', 'month', 'year', 'county_y', 'state_y','2020',
          'median_listing_price', 'median_listing_price_mm','median_listing_price_yy', 
          'active_listing_count', 'active_listing_count_mm', 'active_listing_count_yy',
          'median_days_on_market', 'median_days_on_market_mm', 'median_days_on_market_yy', 
          'new_listing_count', 'new_listing_count_mm','new_listing_count_yy', 
          'price_increased_count','price_increased_count_mm', 'price_increased_count_yy',
          'price_reduced_count', 'price_reduced_count_mm', 'price_reduced_count_yy', 
          'pending_listing_count', 'pending_listing_count_mm', 'pending_listing_count_yy',
          'median_listing_price_per_square_foot', 'median_listing_price_per_square_foot_mm',
          'median_listing_price_per_square_foot_yy', 'median_square_feet',
          'median_square_feet_mm', 'median_square_feet_yy', 'average_listing_price', 
          'average_listing_price_mm', 'average_listing_price_yy', 'total_listing_count',
          'total_listing_count_mm', 'total_listing_count_yy', 'pending_ratio',
          'pending_ratio_mm', 'pending_ratio_yy', 'quality_flag'] 
df = df[column]
df = df.rename(columns = {'county_y': 'county', 'state_y': 'state', '2020':'density'})
df.sample(3).T

,99650,48399,75298
FIPS,29205,17073,22045
date,2021-11-01,2020-01-01,2019-04-01
month,11,1,4
year,2021,2020,2019
county,Shelby County,Henry County,Iberia Parish
state,MO,IL,LA
density,12,59,121
median_listing_price,127500,99999,143514
median_listing_price_mm,-0.0192,0.0106,0.007
median_listing_price_yy,0.5549,-0.0426,-0.0917
active_listing_count,10,158,252
active_listing_count_mm,-0.0909,-0.1073,0.0544
active_listing_count_yy,0.25,-0.0539,-0.0079
median_days_on_market,81,101,103
median_days_on_market_mm,0.6429,0.1038,-0.1825
median_days_on_market_yy,-0.3149,0.116,0.2047
new_listing_count,0,28,44
new_listing_count_mm,-1,0.1667,0
new_listing_count_yy,NaN,0.4,-0.2143
price_increased_count,0,0,0
price_increased_count_mm,NaN,NaN,-1
price_increased_count_yy,NaN,NaN,NaN
price_reduced_count,4,20,68
price_reduced_count_mm,0,0,0.2143
price_reduced_count_yy,0,-0.1667,0.0625
pending_listing_count,4,32,60
pending_listing_count_mm,0.3333,0.2308,-0.1045
pending_listing_count_yy,0.3333,0.0323,0.1765
median_listing_price_per_square_foot,69,64,74
median_listing_price_per_square_foot_mm,-0.0175,0.0132,-0.0229
median_listing_price_per_square_foot_yy,0.1318,-0.1247,-0.0946
median_square_feet,1803,1438,1901
median_square_feet_mm,0.0017,-0.03,-0.0011
median_square_feet_yy,0.5,0.0007,0.0071
average_listing_price,200046,124273,182557
average_listing_price_mm,-0.0451,-0.0051,-0.0043
average_listing_price_yy,0.9985,-0.0777,-0.1011
total_listing_count,14,191,310
total_listing_count_mm,0,-0.0498,0.0231
total_listing_count_yy,0.2727,-0.0255,0.0131
pending_ratio,0.4,0.2025,0.2381
pending_ratio_mm,0.1273,0.0556,-0.0422
pending_ratio_yy,0.025,0.0169,0.0373
quality_flag,1,0,1

In [16]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
FIPS,207398.0,3.033657e+04,15147.245609,1001.0000,18171.0000,29155.0000,45063.0000,5.604500e+04
month,207398.0,6.687273e+00,3.486172,1.0000,4.0000,7.0000,10.0000,1.200000e+01
year,207398.0,2.018778e+03,1.635775,2016.0000,2017.0000,2019.0000,2020.0000,2.022000e+03
density,207398.0,2.779607e+02,1864.876218,0.0000,17.0000,45.0000,120.0000,7.421100e+04
median_listing_price,207368.0,2.305248e+05,210609.359470,2382.0000,133950.0000,186609.0000,279000.0000,1.680000e+07
median_listing_price_mm,170148.0,2.199160e-02,0.921066,-0.9947,-0.0252,0.0000,0.0342,3.134416e+02
median_listing_price_yy,169341.0,1.322187e-01,1.609543,-0.9947,-0.0253,0.0622,0.1737,3.998025e+02
active_listing_count,207368.0,3.496528e+02,969.359650,0.0000,31.0000,95.0000,289.0000,2.335200e+04
active_listing_count_mm,170076.0,-7.248702e-03,0.220484,-1.0000,-0.0833,-0.0140,0.0443,4.800000e+01
active_listing_count_yy,169220.0,-8.556392e-02,0.985142,-1.0000,-0.3497,-0.1466,0.0163,9.600000e+01
median_days_on_market,207398.0,9.294485e+01,59.523698,0.0000,58.0000,82.0000,113.0000,2.100000e+03
median_days_on_market_mm,170170.0,4.583630e-02,0.596488,-1.0000,-0.0863,0.0417,0.1489,1.350000e+02
median_days_on_market_yy,169360.0,2.064624e-02,1.874630,-1.0000,-0.2600,-0.0870,0.0822,3.465000e+02
new_listing_count,207371.0,1.419730e+02,434.702403,0.0000,8.0000,24.0000,92.0000,1.175200e+04
new_listing_count_mm,145681.0,3.741398e-02,0.583258,-1.0000,-0.2500,0.0000,0.2000,1.050000e+01
new_listing_count_yy,145060.0,4.198177e-02,0.606976,-1.0000,-0.2347,0.0000,0.2000,4.200000e+01
price_increased_count,207371.0,1.270122e+01,57.594624,0.0000,0.0000,0.0000,4.0000,1.732000e+03
price_increased_count_mm,47857.0,-1.619901e-02,0.952166,-1.0000,-0.5000,0.0000,0.2400,3.300000e+01
price_increased_count_yy,48261.0,1.029553e-01,1.430584,-1.0000,-0.7471,-0.1111,0.3357,3.100000e+01
price_reduced_count,207371.0,9.293411e+01,332.113351,0.0000,4.0000,16.0000,56.0000,1.063200e+04
price_reduced_count_mm,133375.0,1.275881e-02,0.606231,-1.0000,-0.3000,0.0000,0.2000,1.000000e+01
price_reduced_count_yy,136469.0,-1.008713e-01,0.653547,-1.0000,-0.5000,-0.1667,0.1000,1.800000e+01
pending_listing_count,186125.0,1.654247e+02,546.459093,0.0000,5.0000,23.0000,94.0000,1.417400e+04
pending_listing_count_mm,151357.0,2.050162e-01,8.285732,-1.0000,-0.1250,0.0000,0.1478,1.731000e+03
pending_listing_count_yy,143288.0,2.449862e+00,33.250815,-1.0000,-0.1204,0.0882,0.5789,3.000000e+03
median_listing_price_per_square_foot,206924.0,1.212616e+02,252.513824,1.0000,77.0000,101.0000,138.0000,8.233800e+04
median_listing_price_per_square_foot_mm,169849.0,2.139022e-02,2.344686,-0.9989,-0.0139,0.0015,0.0243,9.222097e+02
median_listing_price_per_square_foot_yy,168842.0,1.277782e-01,4.311887,-0.9987,0.0002,0.0630,0.1480,1.260936e+03
median_square_feet,206924.0,1.911199e+03,472.396692,4.0000,1646.0000,1851.0000,2094.0000,3.090200e+04
median_square_feet_mm,169849.0,5.872085e-03,0.735066,-0.9957,-0.0198,0.0000,0.0188,2.990000e+02
median_square_feet_yy,168842.0,1.783006e-02,0.909308,-0.9968,-0.0613,0.0000,0.0629,3.630000e+02
average_listing_price,207368.0,3.154985e+05,322564.152970,5000.0000,169416.5000,241867.0000,362337.7500,3.150000e+07
average_listing_price_mm,170148.0,1.694271e-02,0.462751,-0.9896,-0.0236,0.0033,0.0353,1.421821e+02
average_listing_price_yy,169341.0,1.477785e-01,1.657749,-0.9903,-0.0248,0.0657,0.1835,3.041574e+02
total_listing_count,207371.0,4.983311e+02,1412.167337,0.0000,41.0000,127.0000,390.0000,3.323300e+04
total_listing_count_mm,170182.0,-2.356879e-03,0.204774,-1.0000,-0.0704,-0.0079,0.0455,4.800000e+01
total_listing_count_yy,169325.0,-8.990270e-03,1.077872,-1.0000,-0.2407,-0.0941,0.0575,1.490000e+02
pending_ratio,186121.0,inf,NaN,0.0000,0.1028,0.2742,0.6032,inf
quality_flag,170480.0,4.840568e-01,0.499747,0.0000,0.0000,0.0000,1.0000,1.000000e+00

In [18]:
df.to_csv('RE_Density.csv', index=False)